// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTodo(arg1:string):Promise<void>;

export function DeleteTodo(arg1:string):Promise<void>;

export function GetTodoList():Promise<Array<main.ListItem>>;

export function UpdateTodo(arg1:string,arg2:boolean):Promise<void>;
